### PR TITLE
Add `MongoMemoryReplSet` support

### LINKED ISSUE #152: `MongoMemoryReplSet` support
Is it possible to launch a replica set for transaction testing?

### PR DESCRIPTION
**Pull request by arisjulio**
- Add replica set support. It just need to add the `replSet` field in `jest-mongodb-config.js` to start working as a replica set.
- Add test script with replica set enabled

Resolve #152

### CODE REVIEW

**Review by vladgolubev — APPROVED** [review]

**Comment by vladgolubev** [comment]
Thanks for the contribution, @arisjulio!

Would you mind adding a couple of words about this option to the README?

**Comment by arisjulio** [comment]
> Would you mind adding a couple of words about this option to the README?

I'll do it before merging

**Comment by arisjulio** [comment]
@vladgolubev 

> Would you mind adding a couple of words about this option to the README?

Done!

**Comment by vladgolubev** [comment]
@arisjulio thanks!

Published! https://github.com/shelfio/jest-mongodb/releases/tag/v2.2.0

**Comment by dozgunyal** [comment]
Hi, this seems great, Thank you!!!

We now get  "MongoError: database name must be a string." errors when we try to connect to replSet.

```
module.exports = { 
  mongodbMemoryServerOptions: {
    binary: {
      version: '4.0.10',
      skipMD5: true
    },
    autoStart: false,
    instance: {
      dbName: 'jest'
    },
    replSet: {
      count: 3,
      storageEngine: 'wiredTiger',
    },
  }
};
```
We tried with and without dbName in instance.

It seems database name is not in the __MONGO_URI__. 
Are we doing something wrong or could you add the database name in the URI?

Should I open a new issue?

**Pull request merged**
