### PR TITLE
Updated readme. fixes #109

### LINKED ISSUE #109: global.__MONGO_URI__ is undefined
Following readme, but got `global.__MONGO_URI__` undefined.

Do we need other steps to setup global env?

### PR DESCRIPTION
**Pull request by natac13**
I was stuck on this and thought after searching the issues #109, saw that a couple other people had the same issue. I just thought it would be nice to add in in the readme. Hope this works for you!
Have a great day.

### CODE REVIEW

**Comment by vladgolubev** [comment]
You're right @natac13, since there is a preset used, there is no need for `testEnvironment` anymore. Thanks for bringing this up!

**Comment by natac13** [comment]
Hey, Sorry if I miss understand why my change was removed, but is it not a good idea to let everyone know in the readme.md that the `testEnvironment` field should be commented out? I believe it should be explicitly stated(which was my goal by adding to the readme), since when someone runs `jest --init` it will ask what environment you are using and then create the `config` file with that line filled out. Then if someone, like myself, adds this preset package to test with Mongo, there will be an error since the `__MONGO_URI__` field is `undefined`.  That lead me to finding issue #109; then adding the commented out line to the readme.

Maybe there is a more appropriate way of letting everyone know to leave off the `testEnvironment` field as this package will set it for them? 

Anyway I do thank you for this preset! Great help for testing with Jest and MongoDB.

**Comment by vladgolubev** [comment]
Hey @natac13 

I just wanted to keep the config minimalistic, that's why I removed it.

I think if people follow the instructions in readme it will work fine regardless what they did with `jest --init`

image


If you create a new `jest.config.js` file and fill it in with the config from README - it will override whatever you had defined before. 

I'll add a note that if you have custom `jest.config.js` don't forget to  remove `testEnvironment`

**Comment by vladgolubev** [comment]
See https://github.com/shelfio/jest-mongodb/commit/a43d5b162b870c39c1cc16629ea0544502ae9edb

**Comment by natac13** [comment]
@vladgolubev Awesome! Thanks again.

**Comment by vladgolubev** [comment]
Thanks for bringing this up @natac13!

**Pull request merged**
