### PR TITLE
feat: increase mongodb version

### PR DESCRIPTION
**Pull request by icco**
This does a few things:

 - fixes mongodb versions to fix https://github.com/shelfio/jest-mongodb/issues/437
 - fixes circleci to fix https://github.com/shelfio/jest-mongodb/pull/431, https://github.com/shelfio/jest-mongodb/pull/432 and https://github.com/shelfio/jest-mongodb/pull/433 
 - ups mongodb memory server to fix https://github.com/shelfio/jest-mongodb/pull/418

### CODE REVIEW

**Comment by vladholubiev** [comment]
@harazdovskiy could you please take a look if nothing breaks, tests pass, and publish a new version?

**Comment by harazdovskiy** [comment]
Checked locally, merging! Thanks @icco for being patient and crafting this pull request❤️

CleanShot 2023-11-23 at 00 57 15@2x

**Comment by harazdovskiy** [comment]
@icco you can check changes in [v4.2.0](https://github.com/shelfio/jest-mongodb/releases/tag/v4.2.0)

**Comment by icco** [comment]
Thank you!

**Comment by erosval** [comment]
Thank you! Unfortunately, the test cases I implemented now no longer work as before when switching from mongodb driver 5.9.1 to 6.3.0.

I have several test cases and it would be complicated to report them but some queries return "undefined", does this happen to others too?

**Comment by icco** [comment]
> Thank you! Unfortunately, the test cases I implemented now no longer work as before when switching from mongodb driver 5.9.1 to 6.3.0.
> 
> I have several test cases and it would be complicated to report them but some queries return "undefined", does this happen to others too?

Did you follow Mongo's upgrade documentation? https://www.mongodb.com/docs/drivers/node/current/upgrade/#version-6.x-breaking-changes we're still rolling out, but some of the return objects have changed.

**Comment by erosval** [comment]
Yes of course, when I run tests on a real mongodb database (v.7) everything works as expected

**Pull request merged**
